# name: calendar_for_ubrainians
name: table_calendar

description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.0.7

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
